version: "3.9"
services:
    web:
        build: .
        volumes:
            - temp-vendor:/work/vendor
            - .:/work
        ports:
            - '8000:8000'
    db:
        image: mysql:5.7
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: laravel_local
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - db-store:/var/lib/mysql
volumes:
    temp-vendor: {}
    db-store: {}
